version: "3"
services:

  java-app:
    container_name: my-java-app1
    build: .
    image: "my-new-java-image"
    ports:
      - "8084:8080"
    depends_on:
      - db
    environment:
      # we overwrite the props in application.properties:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/exchange
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/exchange # db = the name of the container; localhost DOES NOT work; "host.docker.internal" works
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres
    restart: always
    ports: # optional; we set it to be able to access it from our local computer
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exchange
